language: java
sudo: false

services:
  - postgresql
before_script:
  - psql -c 'create database travistest;' -U postgres

script: mvn clean verify -Dspring.config.location=$TRAVIS_BUILD_DIR/.travis.properties
