language: java
sudo: false

services:
  - postgresql
before_script:
  - psql -C 'create database travistest;' -U postgres

script: mvn clean verify -Dspring.datasource.url=jdbc:postgresql://localhost:5432/travistest -Dspring.datasource.username=postgres -Dspring.datasource.password=
